#!/usr/bin/env python3

import sys

from rqt_rc_steering.rqt_rc_calibration import RCSteering
from rqt_gui.main import Main

plugin = 'RCSteering'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
# sys.exit(main.main(sys.argv, standalone='rqt_rc_steering.robot_steering.Fucking'))
